Iniciando colaboração
EuAndreh/hinario-espirita pull request #14
Opened 2017-08-04 19:09 UTC by EuPaulo

Adicionei músicas, coloquei o flag `--halt-on-error` no comando `pdflatex` no arquivos 'hinarios.sh', adicionei o arranjo de "Pelo Mestre com amor".

2017-08-04 23:42 UTC, EuAndreh requested changes
Fica mais difícil de acompanhar o ritmo quando não tem as barras de compasso. Mesmo que elas sejam só opcionais, é mais fácil de ler e de pegar erro.

E não precisa deixar o nome do arquivo como "incompleto".

Mais uma coisa: porque você deletou os "Hinário.pdf", "Slides.pdf" etc.?

Olhei só os arquivos lilypond agora, vou dar uma olhada no latex mais tarde

2017-08-04 23:42 UTC, EuAndreh commented on Arranjos/Pelo Mestre com amor (incompleto...)/Willi-de-Barros-Pelo-Mestre-com-Amor.ly
> +  fis8 g4 fis8 fis8 e4 d8 e8 fis4 fis8 fis8 e8 d8 e8
Na real, a muitos desses grupos melódicos são quiálteras, pela música inteira.

Nessa linha, todas menos as últimas quatro, que são colcheias.

Elas são [tuples](http://lilypond.org/doc/v2.18/Documentation/notation/writing-rhythms#tuplets) no LilyPond.

2017-08-04 23:42 UTC, EuAndreh commented on Arranjos/Pelo Mestre com amor (incompleto...)/Willi-de-Barros-Pelo-Mestre-com-Amor.ly
> +    {d2 r4 d8 e8}
A oitava aqui ficou errada, acho que é uma oitava abaixo.

2017-08-04 23:42 UTC, EuAndreh commented on Arranjos/Pelo Mestre com amor (incompleto...)/Willi-de-Barros-Pelo-Mestre-com-Amor.ly
> +%  A -- guar -- dan -- do a pri -- ma -- ve -- ra
Como tem um ritornelo com a mesma melodia só que com letras diferentes você tem que marcar isso na melodia, mas não me lembro exatamente como. Posso dar uma pesquisada se você precisar de ajuda nisso.

2017-08-04 23:42 UTC, EuAndreh commented on Arranjos/Pelo Mestre com amor (incompleto...)/Willi-de-Barros-Pelo-Mestre-com-Amor.ly
> +  a'8 d,2. d8 b'8 a4 g4 fis4 e8~ e2.~ e8 a,8
Deixar uma mínima pontuada que começa no contratempo é um pouco esquisito de se ler. Acho que deixaria o ritmo mais claro marcando onde estão os contratempos com algo tipo:

```lilypond
a'8 d,~ d2~ d8 d |
```

2017-08-04 23:42 UTC, EuAndreh commented on hinarios.sh
> +  pdflatex -halt-on-error "$1.tex" > /dev/null
:clap:

2017-08-04 23:43 UTC, EuAndreh commented
Também, faltaram os acordes no LilyPond.

2017-08-24 04:30 UTC, EuAndreh requested changes

2017-08-24 04:30 UTC, EuAndreh commented on .log
> +This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex 2017.3.30)  11 AUG 2017 23:40
Esse arquivo não fica commitado. Adiciona ele no `.gitignore` e roda `git rm --cached .`

2017-08-24 04:30 UTC, EuAndreh commented on Cifras.tex
> +\newcommand{\songlink}[2]{\hyperlink{#1}{#2}}
O que é isso?

2017-08-24 04:34 UTC, EuPaulo commented on Cifras.tex
> +\newcommand{\songlink}[2]{\hyperlink{#1}{#2}}
Estava tendo problema para gerar os links do hinário. Achei a solução [aqui](https://tex.stackexchange.com/questions/331277/undefined-control-sequence-on-idxrefsfont-relax-songlink-on-titleidx-sbx/333081) e na [documentação](http://songs.sourceforge.net/songsdoc/songs.html#sec11.6.3).

2017-08-24 04:37 UTC, EuPaulo commented on .log
> +This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex 2017.3.30)  11 AUG 2017 23:40
Feito

2017-10-14 04:20 UTC, EuPaulo commented
Acho que consegui. Dá uma revisada aí.

2017-10-15 01:35 UTC, merged